import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { NeueHaas } from "@/utils/custom-font";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${NeueHaas.className} px-[200px]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
